apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
spec:
  selector:
    matchLabels:
      run: karsajobs
  replicas: 1
  template:
    metadata:
      labels:
        run: karsajobs
    spec:
      containers:
      - name: karsajobs
        image: ghcr.io/mangorte/karsajobs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGO_HOST
          value: mongo-service
      imagePullSecrets:
      - name: githubreg