apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    run: karsajobs
spec:
  type: NodePort
  selector:
    run: karsajobs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30010