apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    run: karsajobs-ui
spec:
  type: NodePort
  selector:
    run: karsajobs-ui
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000