apiVersion: v1
kind: Secret
metadata:
  name: githubreg
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJiV0Z1WjA5U1ZFVTZaMmh3WDJ4U01XbE9VVGg2T0RGMWQxVlhjSFl6U1hrM2VESnpSSGN6VUdKS09UQmxUbTB4VlE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson